### ISSUE TITLE
Character entity

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#1]
Replace the & symbol with it's character entity reference `&amp;`

https://github.com/cubelist/prj-rev-bwfs-dasmoto/blob/0f374d3b4a4a78c7c90bc3eba5e1f1198b9ac511/Dasmotos%20Arts%20%26%20Crafts/index.html#L4

**Comment by cubelist** [comment]
Changed and merged with master branch.
