### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#2]
Great job commenting your HTML file! Just make sure to indent the comments correctly!

https://github.com/cubelist/prj-rev-bwfs-dasmoto/blob/0f374d3b4a4a78c7c90bc3eba5e1f1198b9ac511/Dasmotos%20Arts%20%26%20Crafts/index.html#L9

**Comment by cubelist** [comment]
Done and committed to master branch.
