### ISSUE TITLE
Replace a tag with a span tag

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#3]
Considering the prices aren't really links consider surrounding them with a span with the same class that you are currently using. This allows you to still apply CSS to each individual price. 

https://github.com/cubelist/prj-rev-bwfs-dasmoto/blob/0f374d3b4a4a78c7c90bc3eba5e1f1198b9ac511/Dasmotos%20Arts%20%26%20Crafts/index.html#L20

**Comment by cubelist** [comment]
Ok I think I did this correctly!
