### ISSUE TITLE
Avoid using breaks back to back

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#4]
It's usually recommended to avoid using two breaks in a single line.

Here is an [alternate](https://gist.github.com/jim-rosales/3ff227d8eecb6867066259fc778020ca) HTML structure that you can incorporate. 

https://github.com/cubelist/prj-rev-bwfs-dasmoto/blob/0f374d3b4a4a78c7c90bc3eba5e1f1198b9ac511/Dasmotos%20Arts%20%26%20Crafts/index.html#L15

**Comment by cubelist** [comment]
Ok thanks
