### ISSUE TITLE
Reduce duplicate CSS stlyes

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#5]
Try to analyze if you are declaring duplicate CSS styles and if you are try to declare them in such a way that you only incorporate them once. This reduces the amount of duplicate CSS that you have to write.

For example the font Helvetica is used throughout your page. Instead of declaring the font-family for each individual section you can apply it throughout your page using this [example](https://gist.github.com/jim-rosales/d9db5f5912821f9831305950aac57f1f) 

https://github.com/cubelist/prj-rev-bwfs-dasmoto/blob/0f374d3b4a4a78c7c90bc3eba5e1f1198b9ac511/Dasmotos%20Arts%20%26%20Crafts/resources/css/style.css#L1

**Comment by cubelist** [comment]
ok
