### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [cubelist/prj-rev-bwfs-dasmoto#6]
Grade: Meets Expectations

Summary:
Darren, congrats on finishing the Dasmoto project! You did a fine job commenting your HTML file and using correct indentation. Don't forget it is also recommended that you comment your CSS file, as your projects become more complicated they will help you visually distinguish different sections in your code. 

One recommendation I have is to try and reduce duplicate CSS styles. Take a look at the gist example I gave, declaring CSS in that manner allows you to be more efficient when writing code which is always a plus!

As a challenge try adding [gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) to your page. This will allow you to explore another type of styling you may not have used already.

**Comment by cubelist** [comment]
Thanks Jim - really appreciate the feedback!
